### ISSUE TITLE
Missing dependency Stratsys.Core.Apis

### ISSUE THREAD

**Issue by oledid** [stratsys/Stratsys.Apis.v1#2]
Hi

This library cannot be built without the Stratsys.Core.Apis dependency, which probably is private.

**Comment by david-ernstsson-stratsys** [comment]
Hi @oledid 

This NuGet package should have been tagged as deprecated, sorry about that. For any references of how to integrate with Stratsys APIs please refer to our swagger api documentation and/or your Stratsys integration consultant.

Best regards, David
